-- V1: core user identity + latest computed insights.
-- Runs in the v2 schema (spring.flyway.default-schema). Never edit after it has been applied:
-- Flyway checksums every migration, so changes go in a new V2__, V3__ ... file.

CREATE TABLE users (
    github_id              BIGINT       PRIMARY KEY,           -- GitHub's id, not generated by us
    login                  VARCHAR(39)  NOT NULL,              -- GitHub usernames are max 39 chars
    email                  VARCHAR(320),                       -- null until fetched / if none verified
    encrypted_github_token TEXT,                               -- AES-GCM, Base64 (Phase 6)
    alerts_enabled         BOOLEAN      NOT NULL DEFAULT FALSE, -- opt-in, not opt-out
    no_commit_days         INT          NOT NULL DEFAULT 3
                                        CHECK (no_commit_days BETWEEN 1 AND 30),
    public_profile         BOOLEAN      NOT NULL DEFAULT FALSE, -- opt-in to leaderboards
    needs_reauth           BOOLEAN      NOT NULL DEFAULT FALSE, -- token revoked, stop syncing
    last_synced_at         TIMESTAMPTZ,
    created_at             TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_users_login ON users (login);

-- 1:1 with users via a shared primary key (@MapsId): an insights row cannot exist without its user.
CREATE TABLE insights (
    user_id       BIGINT      PRIMARY KEY REFERENCES users (github_id) ON DELETE CASCADE,
    stats         JSONB       NOT NULL DEFAULT '{}'::jsonb,
    archetype     VARCHAR(32) CHECK (archetype IN (
                      'BUG_HUNTER', 'OPEN_SOURCE_HERO', 'SOFTWARE_ARCHITECT',
                      'WEEKEND_WARRIOR', 'CODE_CRUSADER')),
    roast         TEXT,
    weekly_review TEXT,
    craft_review  TEXT,
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
